### ISSUE TITLE
Strange values for HIELOW

### ISSUE THREAD

**Issue by ohinder** [JuliaSmoothOptimizers/CUTEst.jl#119]
Hey,

I have been using CUTEst.jl and noticed that the "HIELOW" problem (and some other hierarchical logit models) seem to have unbounded objectives. For example, with "HIELOW" if i set 
x = [0.0, 0.0, 1e20] 

I get an objective value of:
-5.746190126842027e22

Which doesn't really make sense (the problem is min -log like).

**Comment by dpo** [comment]
Due to the way HIELOW is implemented, there are variable settings that yield -infinity as objective value. I've contacted the author of the problem in the past but unfortunately, the technical report describing the problem no longer appears to be available. Scaling the problem may help but I haven't experimented much.

**Comment by ohinder** [comment]
thanks!

**Comment by abelsiqueira** [comment]
Closing as it can't be solved here.
