### ISSUE TITLE
Problem in jac_structure!()

### ISSUE THREAD

**Issue by PEPERSO** [JuliaSmoothOptimizers/CUTEst.jl#199]
Hi, there is a problem in ```jac_structure!()```. 

Because of the dispatch in julia, if we run 
 ```julia> jac_structure!(cutestmodel, Int64[...], Int64[...])``` 
it works, because the function ```jac_structure!(nlp :: CUTEstModel, rows :: AbstractVector{<:Integer}, cols :: AbstractVector{<:Integer})```, line 227 of ```julia_interace.jl``` will create ```rows``` and ```cols``` vecteur of the right length, to pass them to ```jac_structure!(nlp :: CUTEstModel, rows :: Vector{Int32}, cols :: Vector{Int32})```, line 198. 

But, if we run 
```julia> jac_structure!(cutestmodel, Int32[...], Int32[...])``` 
with wrong sized vectors, we get : 
```ERROR: DimensionMismatch("array could not be broadcast to match destination")```
because of line 208 and 209 in function ```jac_structure!(nlp :: CUTEstModel, rows :: Vector{Int32}, cols :: Vector{Int32})```. 

The same issue is in ```hess_structure!``` too.

Could you correct that please ?

**Comment by abelsiqueira** [comment]
Were you trying to pass a larger array to `jac_structure!`? The correct size should be available in `nlp.meta.nnzj`.

**Comment by dpo** [comment]
Thank you. See #200.

**Comment by dpo** [comment]
When a problem is embedded into another, it's common to pass arrays that are larger than necessary to the `structure!()`methods, so it should be allowed. In the case of CUTEst, it's more efficient to pass the array directly than a view to avoid allocating a new array. That's only because we're calling Fortran behind the scenes.

@PEPERSO Hopefully, #200 fixes it for your use case.
